version: '3.8'

services:
  web:
    build: .
    container_name: django-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=djangoappdb
      - DB_USER=root
      - DB_PASSWORD=Fitz1234
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=Fitz1234
      - MYSQL_DATABASE=djangoappdb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
