apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: django-app
data:
  DB_NAME: "djangoappdb"
  DB_HOST: "mysql-db"
  DB_PORT: "3306"
  ALLOWED_HOSTS: "django-app.local,localhost,127.0.0.1"  # Add this line
  DEBUG: "True"