name: Build and Run Docker Container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (optional, but recommended for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub (optional, if you need to push to a registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 4: Build the Docker image
    - name: Build the Docker image
      run: |
        docker build -t django-app .

    # Step 5: Run the Docker container
    - name: Run the Docker container
      run: |
        docker run -d -p 8000:8000 django-app

    # Step 6: Optionally check if the container is running
    - name: Check if the container is running
      run: |
        docker ps
