name: Build and Run Docker Container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2


    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build the Docker image
      run: |
        docker build -t django-app .


    - name: Run the Docker container
      run: |
        docker run -d -p 8000:8000 django-app


    - name: Check if the container is running
      run: |
        docker ps
